# config/secrets.yml
development:
  secret_key_base: 	__run_rake_secrets_and_copy_the_key_here__

test:
  secret_key_base:         __run_rake_secrets_and_copy_the_key_here__

# config/application.rb
# TODO Remove this in Rails 4.1
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>