# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39d963ccbbcc276cefeebc5b9fd27e2c0239c13aa2a969a7532639ada5508f5f51a543e776f896affdc4a36e034b05337f947fe9802c3bcd4678f2cc2bb581e4

test:
  secret_key_base: bfb90fcbaf1985bc1e270c70867d3be83d7fd87429f6a49bbeb309f58ded294c12984622da767bb227a695b9fb3dccb5c75efb50fe0c004b97ddfb707a003a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
